'use client';

import { useState } from 'react';
import { Search, FileText, LoaderCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

export default function ResearchPage() {
  const [topics, setTopics] = useState('');
  const [isResearching, setIsResearching] = useState(false);
  const [researchResults, setResearchResults] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!topics.trim()) return;
    
    setIsResearching(true);
    
    // Simulate research process
    setTimeout(() => {
      setResearchResults(`Research results for topics: ${topics.split(',').join(', ')}\n\nThis is a placeholder for the actual research results that would be generated by the Scrapybara collaborative agents.`);
      setIsResearching(false);
    }, 2000);
  };

  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-8">Research With Scrapybara Agents</h1>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <Card>
          <CardHeader>
            <CardTitle>Research Topics</CardTitle>
            <CardDescription>
              Enter the topics you want to research, separated by commas
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit}>
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="topics">Topics</Label>
                  <Input
                    id="topics"
                    placeholder="e.g., Artificial Intelligence, Climate Change, Quantum Computing"
                    value={topics}
                    onChange={(e) => setTopics(e.target.value)}
                  />
                </div>
                
                <Button type="submit" disabled={isResearching || !topics.trim()}>
                  {isResearching ? (
                    <>
                      <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />
                      Researching...
                    </>
                  ) : (
                    <>
                      <Search className="mr-2 h-4 w-4" />
                      Start Research
                    </>
                  )}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>Results</CardTitle>
            <CardDescription>
              Research notes generated by the collaborative agents
            </CardDescription>
          </CardHeader>
          <CardContent>
            {isResearching ? (
              <div className="flex flex-col items-center justify-center h-64">
                <LoaderCircle className="h-8 w-8 animate-spin text-blue-500 mb-4" />
                <p className="text-gray-500">Researching topics...</p>
              </div>
            ) : researchResults ? (
              <Textarea
                value={researchResults}
                readOnly
                className="h-64 resize-none font-mono"
              />
            ) : (
              <div className="flex flex-col items-center justify-center h-64 text-gray-400">
                <FileText className="h-16 w-16 mb-4" />
                <p>Research results will appear here</p>
              </div>
            )}
          </CardContent>
          {researchResults && (
            <CardFooter>
              <Button variant="outline" className="w-full" onClick={() => {
                const element = document.createElement("a");
                const file = new Blob([researchResults], {type: 'text/plain'});
                element.href = URL.createObjectURL(file);
                element.download = "research_notes.txt";
                document.body.appendChild(element);
                element.click();
                document.body.removeChild(element);
              }}>
                Download Results
              </Button>
            </CardFooter>
          )}
        </Card>
      </div>
    </div>
  );
}